### ISSUE TITLE
Linux Xbox controller issue 

### ISSUE THREAD

**Issue by michaelwh** [TeamModular/TowBully#10]
With joystick player have to reverse before can move forwards

**Comment by MrBunsy** [comment]
might be this issue... http://pygame.org/project-Windows+Xbox+360+Controller+for+pygame-2945-.html

**Comment by MrBunsy** [comment]
nope I was wrong, this is windows only

**Comment by MrBunsy** [comment]
re-compiling SDL and pygame from latest source on ubuntu did not work to fix this.

**Comment by b0ggyb33** [comment]
The triggers behave differently on linux/windows

**https://github.com/joncoop/pygame-xbox360controller/blob/master/xbox360_controller.py
**
_" Notes: On Windows, both triggers work additively to return a single axis, whereas triggers on Linux and Mac function as independent axes. In this interface, triggers will behave additively for all platforms so that pygame controllers will work consistently on each platform. Also note that the value returned is on windows is multiplied by -1 so that negative is to the left and positive to the right to be consistent with stick axes. On Linux and Mac, trigger axes return 0 if they haven't been used yet. Once used, an unpulled trigger returns 1 and pulled returns -1. The trigger_used booleans keep the math right for triggers prior to use."_

**Comment by MrBunsy** [comment]
fixed and now in master
